### ISSUE TITLE
[iOS] Bounds 와 Frame 의 차이점을 설명하시오.

### ISSUE THREAD

**Issue by motosw3600** [Pangyo-in-house-cafe/CS#1]

**Comment by motosw3600** [comment]
https://far-leather-50e.notion.site/551446a9b13e4828b46bcac61e1ca14d

**Comment by motosw3600** [comment]
https://motosw3600.tistory.com/24?category=905833

**Comment by MINRYUL** [comment]
https://velog.io/@rlarudfbf1234/Bounds%EC%99%80-Frame-%EC%9D%98-%EC%B0%A8%EC%9D%B4%EC%A0%90

**Comment by hj56775** [comment]
https://velog.io/@hj56775/Frame-Bounds

**Comment by dozzing31** [comment]
https://alive-angora-b93.notion.site/Bounds-Frame-12497f03073942649686dc83834eb1e0
