### ISSUE TITLE
[iOS] Retain Count 방식에 대해 설명하시오.

### ISSUE THREAD

**Issue by MINRYUL** [Pangyo-in-house-cafe/CS#10]

**Comment by motosw3600** [comment]
https://far-leather-50e.notion.site/Retain-Count-c6a771dba6be4a3fb5dbb043e9aacfe0

**Comment by dozzing31** [comment]
https://alive-angora-b93.notion.site/RetainCount-7070c687623f445ca9ae57ac5c311af4

**Comment by hj56775** [comment]
https://h4njun.tistory.com/entry/ARCAutomatic-Reference-Counting

**Comment by MINRYUL** [comment]
https://befitting-yam-c92.notion.site/Retain-Count-885b717284844c288005ebff9a912e09
