### ISSUE TITLE
[iOS] hugging, resistance에 대해서 설명하시오.

### ISSUE THREAD

**Issue by MINRYUL** [Pangyo-in-house-cafe/CS#11]

**Comment by motosw3600** [comment]
https://far-leather-50e.notion.site/hugging-resistance-fa4974f414ac4da6a50e314216494b8c

**Comment by dozzing31** [comment]
https://alive-angora-b93.notion.site/Hugging-Resistance-77a6c6172406493d960babbd159f2b74

**Comment by MINRYUL** [comment]
https://befitting-yam-c92.notion.site/hugging-resistance-136ff13c1d7147f39f8d1c84ade98caf

**Comment by hj56775** [comment]
https://h4njun.tistory.com/entry/Hugging-Compression-Resistance
