### ISSUE TITLE
[iOS] 스토리보드를 이용했을때의 장단점을 설명하시오.

### ISSUE THREAD

**Issue by MINRYUL** [Pangyo-in-house-cafe/CS#12]

**Comment by motosw3600** [comment]
https://far-leather-50e.notion.site/Storyboard-f4d11f317d47418780eee33e76ac0686

**Comment by dozzing31** [comment]
https://alive-angora-b93.notion.site/Storyboard-476fc416828c46c39a70da2070acd204

**Comment by MINRYUL** [comment]
https://befitting-yam-c92.notion.site/df45086c8d454ea1b6c0b118eee4ca94

**Comment by hj56775** [comment]
https://h4njun.tistory.com/entry/Storyboard-VS-CodeProgrammatically
