### ISSUE TITLE
[iOS] setNeedsLayout와 setNeedsDisplay의 차이에 대해 설명하시오.

### ISSUE THREAD

**Issue by motosw3600** [Pangyo-in-house-cafe/CS#13]

**Comment by MINRYUL** [comment]
https://befitting-yam-c92.notion.site/setNeedsLayout-setNeedsDisplay-efb355c436d94605b17e66bca4285c20

**Comment by motosw3600** [comment]
https://far-leather-50e.notion.site/setNeedsLayout-setNeedsDisplay-bdba6deab1194da48666bc71709076a1

**Comment by dozzing31** [comment]
https://alive-angora-b93.notion.site/setNeedsLayout-setNeedsDisplay-00949af293644f95ad3a3a4c4f567351

**Comment by hj56775** [comment]
https://h4njun.tistory.com/entry/setNeedsDisplay-setNeedsLayout
