### ISSUE TITLE
[Swift] 탈출 클로저에 대하여 설명하시오.

### ISSUE THREAD

**Issue by motosw3600** [Pangyo-in-house-cafe/CS#14]

**Comment by MINRYUL** [comment]
https://befitting-yam-c92.notion.site/Escaping-Closure-f75628d28b7e4ea7aaafaf5fd9c6d5be

**Comment by motosw3600** [comment]
https://far-leather-50e.notion.site/escaping-closure-ba5c97f72291410da8a3eedbe160cb4d

**Comment by dozzing31** [comment]
https://alive-angora-b93.notion.site/escaping-closure-82c6edc3955046d898d24f600837b159

**Comment by hj56775** [comment]
https://h4njun.tistory.com/entry/escaping-closure탈출-클로저
