### ISSUE TITLE
[Swift] Codable에 대해서 설명하시오

### ISSUE THREAD

**Issue by dozzing31** [Pangyo-in-house-cafe/CS#15]

**Comment by MINRYUL** [comment]
https://befitting-yam-c92.notion.site/Codable-32fb744333bb4a09a4b826c7333e5b9b

**Comment by motosw3600** [comment]
https://far-leather-50e.notion.site/Codable-502707a80d2b45faaca3a6fcc3738e1b

**Comment by dozzing31** [comment]
https://alive-angora-b93.notion.site/Codable-fb5fb85a8fa54db69a48b3bdf861089d

**Comment by hj56775** [comment]
https://h4njun.tistory.com/entry/Codable
