### ISSUE TITLE
[Advanced] NSCoder 클래스는 어떤 상황에서 어떻게 써야 하는지 설명하시오

### ISSUE THREAD

**Issue by dozzing31** [Pangyo-in-house-cafe/CS#16]

**Comment by MINRYUL** [comment]
https://befitting-yam-c92.notion.site/NSCoder-7baaabfc280544f781482b7a744f9a6c

**Comment by hj56775** [comment]
https://h4njun.tistory.com/entry/NSCoder

**Comment by motosw3600** [comment]
https://far-leather-50e.notion.site/NSCoding-NSCoder-d96dc37bc49f41e8bcf3319c6ef9881c

**Comment by dozzing31** [comment]
https://alive-angora-b93.notion.site/NSCoder-65c7af5056924c919b00863287d4e826
