### ISSUE TITLE
[iOS] 실제 디바이스가 없을 경우 개발 환경에서 할 수 있는 것과 없는 것을 설명하시오.

### ISSUE THREAD

**Issue by motosw3600** [Pangyo-in-house-cafe/CS#2]

**Comment by motosw3600** [comment]
https://far-leather-50e.notion.site/551446a9b13e4828b46bcac61e1ca14d

**Comment by MINRYUL** [comment]
https://velog.io/@rlarudfbf1234/%EC%8B%A4%EC%A0%9C-%EB%94%94%EB%B0%94%EC%9D%B4%EC%8A%A4%EA%B0%80-%EC%97%86%EC%9D%84-%EA%B2%BD%EC%9A%B0-iOS-%ED%99%98%EA%B2%BD%EC%97%90%EC%84%9C-%ED%95%A0-%EC%88%98-%EC%9E%88%EB%8A%94-%EA%B2%83%EA%B3%BC-%EC%97%86%EB%8A%94-%EA%B2%83

**Comment by hj56775** [comment]
https://velog.io/@hj56775/개발하는데-실제-디바이스가-필요할까

**Comment by dozzing31** [comment]
https://alive-angora-b93.notion.site/2c10045f52b7450dbe547a3057a5c69a
