### ISSUE TITLE
[swift] struct와 class와 enum의 차이를 설명하시오.

### ISSUE THREAD

**Issue by motosw3600** [Pangyo-in-house-cafe/CS#3]

**Comment by hj56775** [comment]
https://h4njun.tistory.com/4

**Comment by dozzing31** [comment]
https://alive-angora-b93.notion.site/Struct-Class-Enum-32e5200450d04919900217cba8dbde8d

**Comment by motosw3600** [comment]
https://motosw3600.tistory.com/25?category=905834

**Comment by MINRYUL** [comment]
https://www.notion.so/Struct-Class-Enum-7128df1e8d644a20aa28327600f23a61
