### ISSUE TITLE
[iOS] Delegate란 무언인가 설명하고, retain 되는지 안되는지 그 이유를 함께 설명하시오.

### ISSUE THREAD

**Issue by motosw3600** [Pangyo-in-house-cafe/CS#4]

**Comment by dozzing31** [comment]
https://alive-angora-b93.notion.site/Delegate-feat-ARC-611746f45cb94299be49387029c80083

**Comment by motosw3600** [comment]
https://motosw3600.tistory.com/26

**Comment by hj56775** [comment]
https://h4njun.tistory.com/5

**Comment by MINRYUL** [comment]
https://www.notion.so/Delegate-55af552f99be493db754598e0a6e6eac
