### ISSUE TITLE
[iOS] View 객체에 대해 설명하시오.

### ISSUE THREAD

**Issue by MINRYUL** [Pangyo-in-house-cafe/CS#5]

**Comment by MINRYUL** [comment]
https://befitting-yam-c92.notion.site/View-996cf76e4bdc416ba9a06b144cff1c50

**Comment by dozzing31** [comment]
https://alive-angora-b93.notion.site/View-20595c7c6eb44dc18fa61949921af884

**Comment by motosw3600** [comment]
https://motosw3600.tistory.com/28

**Comment by hj56775** [comment]
https://h4njun.tistory.com/6
