### ISSUE TITLE
[swift] String은 왜 subscript로 접근이 안되는지 설명하시오.

### ISSUE THREAD

**Issue by MINRYUL** [Pangyo-in-house-cafe/CS#6]

**Comment by MINRYUL** [comment]
https://befitting-yam-c92.notion.site/String-subscript-8f10f7914db64aa198f75a54ff59ca65

**Comment by dozzing31** [comment]
https://alive-angora-b93.notion.site/String-Subscript-5c4dcb19263a4663bc583867f8403d6a

**Comment by motosw3600** [comment]
https://far-leather-50e.notion.site/String-subscript-08fbef9288ae458da5ec754f72050379

**Comment by hj56775** [comment]
https://h4njun.tistory.com/7
