### ISSUE TITLE
[iOS] ViewController의 생명주기를 설명하시오.

### ISSUE THREAD

**Issue by hj56775** [Pangyo-in-house-cafe/CS#7]

**Comment by hj56775** [comment]
https://h4njun.tistory.com/entry/ViewController-Life-Cycle

**Comment by motosw3600** [comment]
https://motosw3600.tistory.com/6?category=905833

**Comment by MINRYUL** [comment]
https://befitting-yam-c92.notion.site/ViewController-0e6b89d07bdc4ca5b475f8898674aa77

**Comment by dozzing31** [comment]
https://alive-angora-b93.notion.site/ViewController-2ca88afb32b84552ac12eae876398895
