### ISSUE TITLE
[Swift] Hashable이 무엇이고, Equatable을 왜 상속해야 하는지 설명하시오.

### ISSUE THREAD

**Issue by hj56775** [Pangyo-in-house-cafe/CS#8]

**Comment by motosw3600** [comment]
https://far-leather-50e.notion.site/Hashable-Equatable-a1277933b334469bb555561f5a66ae55

**Comment by MINRYUL** [comment]
https://befitting-yam-c92.notion.site/Hashable-Equatable-374ef18349d8448da2f907f9df29633e

**Comment by dozzing31** [comment]
https://alive-angora-b93.notion.site/Hashable-feat-Equatable-667894d86be447459c65c179ca59f234

**Comment by hj56775** [comment]
https://h4njun.tistory.com/entry/Hashable
