### ISSUE TITLE
[iOS] ARC란 무엇인지 설명하시오.

### ISSUE THREAD

**Issue by MINRYUL** [Pangyo-in-house-cafe/CS#9]

**Comment by motosw3600** [comment]
https://motosw3600.tistory.com/5?category=905834

**Comment by dozzing31** [comment]
https://alive-angora-b93.notion.site/ARC-0d86d4d321d449669172af82b625730b

**Comment by hj56775** [comment]
https://h4njun.tistory.com/entry/ARCAutomatic-Reference-Counting

**Comment by MINRYUL** [comment]
https://befitting-yam-c92.notion.site/ARC-1d899827ba204374a17bcc935eb92a8a
